export const testArray = [
  {
    id: 'an-id',
    name: 'some name',
    tags: ['some', 'tags'],
    gameType: 'somegametype',
    provider: 'agreatprovider',
    colorIndex: 1,
  },
  {
    id: 'an-id',
    name: 'some name',
    tags: ['some', 'tags'],
    gameType: 'somegametype',
    provider: 'agreatprovider',
    colorIndex: 1,
  },
  {
    id: 'an-id',
    name: 'some name',
    tags: ['some', 'tags'],
    gameType: 'somegametype',
    provider: 'agreatprovider',
    colorIndex: 1,
  },
  {
    id: 'an-id',
    name: 'some name',
    tags: ['some', 'tags'],
    gameType: 'somegametype',
    provider: 'agreatprovider',
    colorIndex: 1,
  },
  {
    id: 'an-id',
    name: 'some name',
    tags: ['some', 'tags'],
    gameType: 'somegametype',
    provider: 'agreatprovider',
    colorIndex: 1,
  },
  {
    id: 'an-id',
    name: 'some name',
    tags: ['some', 'tags'],
    gameType: 'somegametype',
    provider: 'agreatprovider',
    colorIndex: 1,
  },
];